name: Generate Address

on:
  push:
    branches: [ pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create address
    steps:
      - name: address creator
        id: x
        uses: linuxuserin/create-tor-address@main
        with:
          name: 'x'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: torsite
          build_dir: keys
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}